web-app/config/routes.rb
Rails.application.routes.draw do
	root 'messages#index'
	TheRoleManagementPanel::Routes.mixin(self)
  devise_for :users, except: :new, controllers: { invitations: 'invitations', sessions: 'sessions'}
  as :user do
    get 'user/:id/edit/' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'user/:id' => 'devise/registrations#update', as: 'user_registration'
  end
  resources :users, only: [:index, :destroy]

  resources :categories, except: [:destroy] do
    collection do
      get :archived_categories, as: 'archived'
    end
    member do
      post :archiving
      post :unarchiving
    end
  end

  resources :messages do
    collection do
      post ':id/destroy' => 'messages#archiving', as: 'archiving'
    end
    resources :images, only: [:create]
  end
  post '/messages/:message_id/image' => 'messages#image_save'

  get '/rss_index' => 'rss#rss_index'
  get '/rss_show/:id' => 'rss#rss_show', as: 'rss_show'

  get '/atom_index' => 'rss#atom_index'
  get '/atom_show/:id' => 'rss#atom_show', as: 'atom_show'
end

web-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include TheRole::Controller
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_raven_context

  def role_access_denied
    access_denied_method = TheRole.config.access_denied_method
    return send(access_denied_method) if access_denied_method && respond_to?(access_denied_method)
    the_role_default_access_denied_response
  end

  protected

  def configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:accept_invitation, keys: [:name, :role_id])
  end

  def set_raven_context
    Raven.user_context(id: session[:current_user_id]) # or anything else in session
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end

	def the_role_default_access_denied_response
    access_denied_msg = t(:access_denied, scope: :the_role)

    if request.xhr?
      render json: {
        errors: { the_role: [ access_denied_msg ] },

        controller_name:      controller_path,
        action_name:          action_name,
        has_access_to_action: current_user.try(:has_role?, controller_path, action_name),

        current_user: { id: current_user.try(:id) }

        # owner_check_object: {
        #   owner_check_object_id:    @owner_check_object.try(:id),
        #   owner_check_object_class: @owner_check_object.try(:class).try(:to_s)
        # },

        # has_access_to_object: current_user.try(:owner?, @owner_check_object)
      }, status: 401
    else
      # When the user paste non authorized URL in browser the REFERER is blank and application crash
      if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
        # redirect_to root_path, flash: { error: access_denied_msg }
        render :file => "#{Rails.root}/public/403.html", :status => 403, :layout => false
      else
      	render :file => "#{Rails.root}/public/403.html", :status => 403, :layout => false
        # redirect_to root_path, flash: { error: access_denied_msg }
      end
    end
  end
end

web-app/app/helpers/application_helper.rb
module ApplicationHelper
end

web-app/app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyCity", root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav">
      <li class="dropdown">
        <% if current_user %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Действия<span class="caret"></span></a>
        <% end %>
        <ul class="dropdown-menu">
          <li><%= link_to "Категории", categories_path %></li>
          <li><%= link_to "Сообщения", messages_path %></li>
          <li>
            <%= link_to 'Админ панель',  admin_roles_path if current_user && current_user.admin? %>
          </li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Регистрация", new_user_invitation_path if current_user && current_user.admin? %></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right" id="user_actions">
      <% if user_signed_in? %>
        <li><%= link_to current_user.name, edit_user_registration_path(current_user) %></li>
        <li><%= link_to 'Выход', destroy_user_session_path if current_user %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Все", root_path %></li>
        <li><%= link_to "Ожидают модерации", messages_path(status: :for_moderation) %></li>
        <li><%= link_to "Выполненные", messages_path(status: :done) %></li>
        <li><%= link_to "Актуальные", messages_path(status: :actual) %></li>
        <li><%= link_to "Неактуальные", messages_path(status: :not_relevant) %></li>
      <% end %>
      <li><%= link_to image_tag("rss.png", :alt => "rss feed", size: "20x20"), rss_index_path %></li>
      <li style="visibility: hidden;">Divider</li>
    </ul>
  </div>
</nav>