web-app/config/routes.rb
Rails.application.routes.draw do
	root 'messages#index'
	TheRoleManagementPanel::Routes.mixin(self)
  devise_for :users, except: :new, controllers: { invitations: 'invitations', sessions: 'sessions'}
  as :user do
    get 'user/:id/edit/' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'user/:id' => 'devise/registrations#update', as: 'user_registration'
  end
  resources :users, only: [:index, :destroy]

  resources :categories, except: [:destroy] do
    collection do
      get :archived_categories, as: 'archived'
    end
    member do
      post :archiving
      post :unarchiving
    end
  end

  resources :messages do
    collection do
      post ':id/destroy' => 'messages#archiving', as: 'archiving'
    end
    resources :images, only: [:create]
  end
  post '/messages/:message_id/image' => 'messages#image_save'

  get '/rss_index' => 'rss#rss_index'
  get '/rss_show/:id' => 'rss#rss_show', as: 'rss_show'

  get '/atom_index' => 'rss#atom_index'
  get '/atom_show/:id' => 'rss#atom_show', as: 'atom_show'
end

web-app/app/models/message.rb
class Message < ApplicationRecord

	enum status: [ :for_moderation, :done, :actual, :not_relevant, :hidden ]

	has_many :images, dependent: :destroy
	belongs_to :category

	geocoded_by :address
	reverse_geocoded_by :latitude, :longitude

	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
	after_validation :reverse_geocode, if: ->(obj){ obj.latitude.present? and obj.longitude.present? and obj.address.nil? }

    paginates_per 10

end

web-app/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:update, :show, :edit, :archiving]
  before_action :role_required, except: [:create, :image_save]  # проверяет роль юзера
  skip_before_action :authenticate_user!, only: [:create, :image_save]

  def index
    if params[:status].nil?
      @messages = Message.all.where.not(status: :hidden).order(created_at: :desc).order(:body).page(params[:page])
      @title = "Все сообщения"
    else
      @messages = Message.all.where(status: params[:status]).order(created_at: :desc).order(:body).page(params[:page])
      @title =
      case params[:status]
      when "new_message"
        "Новые сообщения"
      when "done"
        "Выполненные сообщения"
      when "actual"
        "Актуальные сообщения"
      when "not_relevant"
        "Неактуальные сообщения"
      end
    end
  end

  def create
    @message = Message.create(message_params)
    render plain: @message.id
  end

  def image_save
    Image.create(image: params[:image], message_id: params[:message_id])
  end

  def show
    @images = @message.images
    @hash = Gmaps4rails.build_markers(@message) do |message, marker|
      marker.lat message.latitude
      marker.lng message.longitude
      marker.infowindow message.address
    end
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    if @message.update(message_params)
      redirect_back(fallback_location: root_path)
      flash[:success] = "Статус сообщения успешно изменен!"
    else
      render 'edit'
    end
  end

  def archiving
    @message.status = "hidden"
    @message.save
    flash[:success] = "Сообщение успешно удалено!"
    redirect_to root_path
  end

  private
  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:body, :latitude, :longitude, :address, :status, :category_id, :sender_name, :sender_id)
  end

  def image_params
    params.require(:image).permit({image: []})
  end

end

web-app/app/helpers/messages_helper.rb
module MessagesHelper
	def panel_type(message)
		panel_type =
			case message.status
			when "new_message"
				"info"
			when "actual"
				"warning"
			when "done"
				"success"
			when "not_relevant"
				"default"
			else
				"primary"
			end
	end

end

web-app/app/views/messages/_change_category.html.erb
<%= form_for message, url: message_path(message) do |f| %>
	<div class="col-md-6">
		<%= f.collection_select :category_id, Category.all, :id, :title, {:include_blank => false}, {:class => 'form-control'} %>
  </div>
  <div class="col-md-6">
		<%= f.submit 'Обновить категорию', class: 'btn btn-primary btn' %>
  </div><br>

<% end %>

web-app/app/views/messages/_change_status.html.erb
<%= form_for message, url: message_path(message) do |f| %>
	<div class="col-md-6">
	<%= f.select(:status,
							options_for_select([['На модерацию', message.status = 'for_moderation'],
																	['Выполнено', message.status = 'done'],
																	['Актуально', message.status = 'actual'],
																	['Не релевантно', message.status = 'not_relevant']]),
							{:include_blank => false}, {:class => 'form-control'}) %>
	</div>
	<div class="col-md-6">
	<%= f.submit 'Обновить статус', class: 'btn btn-primary btn' %>
	</div><br>
<% end %>

web-app/app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
	<%= f.input :body,label: "Текст" %>
	<%= f.input :category_id, label: "Категория", collection: Category.all %>
	<%= f.submit %>
<% end %>

web-app/app/views/messages/edit.html.erb
<h1>Редактирование</h1>
<%= render "form" %>

web-app/app/views/messages/index.html.erb
<%= render partial: 'shared/list_messages.html.erb'%>

web-app/app/views/messages/show.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyBRkajFk38d_24oT0mo8rkMWb1_fJHSMW8"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<link  href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet"> <!-- 3 KB -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script> <!-- 16 KB --> <!-- only if you need custom infoboxes -->

<div class="row my-4">
  <% unless @message.latitude.nil? && @images.count == 0 %>
    <div class="col-md-12">
      <div class="fotorama col-lg-6" data-nav="thumbs" data-loop="true" data-width="600" data-max-width="100%" data-allowfullscreen="true">

          <%= image_tag("medium_default.jpg") if @images.count == 0 %>
          <% unless @images.count == 0 %>
            <% @images.each do |image| %>
              <%= image_tag(image.image_url(:medium)) %>
            <% end %>
          <% end %>
      </div>

      <div class="col-lg-6" style="display: flex; flex-direction: row; justify-content: space-between;">
        <div style='width: 600px;'>
          <div id="map" style='width: 540px; height: 324px;'></div>
        </div>
      </div>
    </div>
  <% end %>
<div class="col-md-12">
  <div class="col-lg-6">
    <div class="message-body">
      <hr>
      <h2 class="card-title"><b>Описание: </b></h2>
      <h2><%= @message.body %></h2>
    </div>
  </div>

  <div class="col-lg-6">
    <hr>
    <h2>Статус: <b><%= I18n.t :"message_status.#{@message.status}" %></b></h2>
    <br />
    <div>
      <%= render partial: 'messages/change_status', locals: { message: @message } %>
    </div>
    <br />
    <hr>
    <h2>Категория: <b><%= @message.category.title %></b></h2>
    <br />
    <div>
      <%= render partial: 'messages/change_category', locals: { message: @message } %>
    </div>
    <br />
    <hr>
    <%= link_to 'Удалить сообщение', archiving_messages_path(@message), method: :post, class: 'btn btn-danger' %>
  </div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {mapTypeId: 'hybrid'}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
    });
</script>