web-app/config/routes.rb
Rails.application.routes.draw do
	root 'messages#index'
	TheRoleManagementPanel::Routes.mixin(self)
  devise_for :users, except: :new, controllers: { invitations: 'invitations', sessions: 'sessions'}
  as :user do
    get 'user/:id/edit/' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'user/:id' => 'devise/registrations#update', as: 'user_registration'
  end
  resources :users, only: [:index, :destroy]

  resources :categories, except: [:destroy] do
    collection do
      get :archived_categories, as: 'archived'
    end
    member do
      post :archiving
      post :unarchiving
    end
  end

  resources :messages do
    collection do
      post ':id/destroy' => 'messages#archiving', as: 'archiving'
    end
    resources :images, only: [:create]
  end
  post '/messages/:message_id/image' => 'messages#image_save'

  get '/rss_index' => 'rss#rss_index'
  get '/rss_show/:id' => 'rss#rss_show', as: 'rss_show'

  get '/atom_index' => 'rss#atom_index'
  get '/atom_show/:id' => 'rss#atom_show', as: 'atom_show'
end

web-app/app/models/category.rb
class Category < ApplicationRecord
	has_many :messages, dependent: :destroy

	validates :title, presence: true, length: {maximum: 40}

  paginates_per 10
end

web-app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :role_required # проверяет роль юзера
  before_action :set_category, only: [:show, :edit, :update, :archiving, :unarchiving]

  def index
    @categories = Category.where(archived: false).order(created_at: :desc).order(:title).page(params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
      flash[:success] = "Категория успешно создана."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to root_path
      flash[:success] = "Категория успешно обновлена."
    else
      render 'edit'
      flash[:danger] = "Ошибка."
    end
  end

  def show
      if params[:status] == 'all'
        @messages = @category.messages.order(created_at: :desc).order(:body).page(params[:page])
      else
        @messages = @category.messages.where(status: params[:status]).order(created_at: :desc).order(:body).page(params[:page])
      end
  end

  def archiving
    @category.archived = true
    @category.save
    flash[:success] = "Категория успешно архивирована."
    redirect_to categories_path
  end

  def unarchiving
    @category.archived = false
    @category.save
    flash[:success] = "Категория успешно восстановлена."
    redirect_to categories_path
  end

  def archived_categories
    @categories = Category.where(archived: true)
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

web-app/app/helpers/categories_helper.rb
module CategoriesHelper
end

web-app/app/views/categories/_form.html.erb
<div class="col-sm-4">
	<%= simple_form_for(@category) do |f| %>
		<%= f.error_notification %>
		<%= f.input :title, label: 'Название', class: 'form-control' %>
		<%= f.submit "Создать", class: 'btn btn-success' %>
	<% end %>
</div>

web-app/app/views/categories/archived_categories.html.erb
<h1>Архивные категории</h1>
<table class="table">
	<tr>
		<th>Название</th>
		<th>Действия</th>
	</tr>

	<% @categories.each do |category| %>
		<tr>
			<td><%= category.title %></td>
			<td><%= link_to 'Восстановить', unarchiving_category_path(category), method: :post, id: "unarchiving_category_#{category.id}" %></td>
		</tr>
	<% end %>
</table>
<%= link_to "Показать все категории", categories_path %>

web-app/app/views/categories/edit.html.erb
<%= render 'form' %>

web-app/app/views/categories/index.html.erb
<h1>Категории</h1>
<table class="table">
	<tr>
		<th>Название</th>
		<th>Действия</th>
	</tr>

	<% @categories.each do |category| %>
		<tr>
			<td><%= link_to category.title, category_path(id: category.id, status: 'all'), id: "category_#{category.id}" %></td>
			<td><%= link_to 'Архивировать', archiving_category_path(category), method: :post, id: "archiving_category_#{category.id}" %></td>
			<td><%= link_to 'Обновить', edit_category_path(category), class: 'update', id: "edit_category_#{category.id}" %></td>
		</tr>
	<% end %>

</table>
<%= paginate @categories %>

<p><%= link_to "Добавить новую категорию", new_category_path, class: "btn btn-success" %></p>
<p><%= link_to "Показать архивные категории", archived_categories_path %></p>

web-app/app/views/categories/new.html.erb
<h2>Создать новую категорию</h2>
<hr>
<%= render 'form' %>

web-app/app/views/categories/show.html.erb
<h2>Сообщения по категории: <b><%= @category.title %></b></h2>
<br />
<div>
  <table class="table table-striped">
    <tr>
      <th>Описание</th>
      <th>Адрес</th>
      <th>Статус</th>
      <th>Действия</th>
    </tr>
    <% @messages.each_with_index do |message, index| %>
      <tr id="message_<%= index %>">
        <td><%= message.body.truncate(30, separator: ' ') %></td>
        <td><%= message.address %></td>
        <td><%= I18n.t :"message_status.#{message.status}" %></td>
        <td><%= link_to "Редактировать", message_path(message.id), class: "btn btn-md btn-info" %></td>
      </tr>
    <% end %>
  </table>
  <%= paginate @messages %>
</div>

<% unless @messages.nil? %>
  <div>
    <ul>
      <li><%= link_to @category.title + ' rss', rss_show_path(@category.id) %></li>
    </ul>
  </div>
<% end %>